version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "build(actions)"
    groups:
      actions-security:
        applies-to: "security-updates"
        patterns:
          - "*"
      actions-minor-patch:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      actions-major:
        applies-to: "version-updates"
        update-types:
          - "major"
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "build(npm)"
    groups:
      frontend-security:
        applies-to: "security-updates"
        patterns:
          - "*"
      frontend-minor-patch:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      frontend-major:
        applies-to: "version-updates"
        update-types:
          - "major"
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "build(cargo)"
    groups:
      rust-security:
        applies-to: "security-updates"
        patterns:
          - "*"
      rust-minor-patch:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      rust-major:
        applies-to: "version-updates"
        update-types:
          - "major"
        patterns:
          - "*"
