name: Coverage

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  coverage:
    name: Coverage metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Run coverage
        run: bun run test:coverage

      - name: Check coverage threshold
        run: bun run coverage:check

      - name: Audit album metadata
        run: bun run album:audit
